services:
  db:
    image: mysql:8.0
    container_name: autolamp-db
    environment:
      MYSQL_DATABASE: autolamp
      MYSQL_USER: autolamp
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: autolamp-app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=autolamp
      - DB_USERNAME=autolamp
      - DB_PASSWORD=secret
    restart: unless-stopped

  composer:
    image: composer:latest
    container_name: autolamp-composer
    volumes:
      - .:/app
    command: install

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: autolamp-phpmyadmin
    depends_on:
      db:
        condition: service_healthy
    environment:
      PMA_HOST: db
      PMA_USER: autolamp
      PMA_PASSWORD: secret
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"
    restart: unless-stopped

volumes:
  db_data:
