name: Laravel CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: autolamp
          MYSQL_USER: autolamp
          MYSQL_PASSWORD: secret
          MYSQL_ROOT_PASSWORD: secret
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, bcmath, zip, pdo_mysql
          coverage: none

      - name: Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

      - name: Setup environment
        run: |
          cp .env.example .env
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=autolamp" >> .env
          echo "DB_USERNAME=autolamp" >> .env
          echo "DB_PASSWORD=secret" >> .env
          php artisan key:generate

      - name: Wait for MySQL
        run: |
          until mysql -h127.0.0.1 -uroot -psecret -e "SELECT 1" &> /dev/null; do
            echo "Waiting for MySQL..."
            sleep 5
          done

      - name: Run migrations
        run: php artisan migrate --force

      - name: Run tests
        run: php artisan test
